### ISSUE TITLE
Stopped working recently

### ISSUE THREAD

**Issue by ghost** [InfernoStats/Brewing#3]
Hi mate. Recently it seems that this has stopped working for me and my mate using it. It just doesnt even detect that they are brewing and doesnt detect when they are finished.

If I turn "infobox state" to "Always" it show both locations as "uninitialized" 

Let me know if there's any more info i can provide.. Cheers
![Untitled](https://user-images.githubusercontent.com/11243032/145187818-29e8bdbf-6397-4778-b5b1-73559a2e6336.png)

**Comment by InfernoStats** [comment]
Uninitialized is probably a result of the client's settings file not being updated. Double check that your client supports `configManager.setRSProfileConfiguration(CONFIG_GROUP, key, obj);`. You could also run the client in Intellij to debug if any of the methods in the plugin are failing.

https://github.com/InfernoStats/Brewing/blob/master/src/main/java/com/infernostats/BrewingPlugin.java#L178

Currently Working for me:
![image](https://user-images.githubusercontent.com/77599829/145246997-81b1860f-b06b-43ab-9455-74fe9398608c.png)

**Comment by InfernoStats** [comment]
It seems your client was more up to date than mine!

```
2021-12-09 11:58:30 [Client] WARN  n.runelite.client.eventbus.EventBus - Uncaught exception in event subscriber
java.lang.NoSuchMethodError: 'java.lang.Object net.runelite.client.config.ConfigManager.getRSProfileConfiguration(java.lang.String, java.lang.String, java.lang.reflect.Type)'
	at com.infernostats.BrewingPlugin.getConfigOpt(BrewingPlugin.java:387)
	at com.infernostats.BrewingPlugin.getConfigBrewingState(BrewingPlugin.java:360)
	at com.infernostats.BrewingPlugin.onGameTick(BrewingPlugin.java:174)
	at net.runelite.client.eventbus.EventBus$Subscriber.invoke(EventBus.java:70)
	at net.runelite.client.eventbus.EventBus.post(EventBus.java:220)
	at net.runelite.client.callback.Hooks.tick(Hooks.java:191)
	at client.doCycle(Client.java:2537)
	at client.i(Client.java)
	at am.u(GameEngine.java:335)
	at am.run(GameEngine.java:314)
	at java.base/java.lang.Thread.run(Thread.java:832)
```

**Comment by ghost** [comment]
Ah yeah I am using a daily updated client. Does this mean that you've been able to replicate the issue?
Cheers

**Comment by InfernoStats** [comment]
@40-Cal-Banana Yes I can reproduce the issue. I'm working on a fix for it now

**Comment by InfernoStats** [comment]
@40-Cal-Banana https://github.com/runelite/plugin-hub/pull/2525
